### ISSUE TITLE
adapt the landing page text

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/vot-diaspora-client#12]

**Comment by mihaelataranu7** [comment]
Pe data de 1 noiembrie 2020 au loc alegerile prezidențiale din Republica Moldova. Cetățenii moldoveni cu drept de vot, care au domiciliul sau reședința în străinătate, pot vota la secție. 
Pentru a afla care sunt pașii pe care trebuie să-i parcurgeți pentru a vota în cadrul acestui tur electoral, consultați ghidul de mai jos.

La alegerile prezidențiale își exercită dreptul de vot în afara țării doar cetățenii moldoveni cu domiciliul sau reședința în străinătate. Află ce ai de făcut pentru a putea vota în țara în care ai domiciliu sau reședința la alegerile din 1 noiembrie 2020.

ATENȚIE!

Pentru a vota în străinătate, aveți nevoie de următoarele acte:
- Pașaportul cetățeanului Republicii Moldova, inclusiv cu termenul de valabilitate expirat, 
- Buletinul de identitate (valabil) cu fișa de însoțire, 
- Livretul de marinar.

Votarea va avea loc în intervalul orelor 07.00 – 21.00 (ora locală a fiecărei secții de votare).

Asigură-te că ai cu tine un pix și o mască de protecție. Fiecare secție de votare va fi dezinfectată la un interval de fiecare 2-3 ore. În fiecare local al secției de votare numărul alegătorilor care vor avea acces în același timp va fi egal cu numărul cabinelor de vot instalate!


Unde stai?
Caută orașul în care locuiești pentru a afla care sunt cele mai apropiate secții de votare.

Informează-ți prietenii
Distribuie aceste informații în social media pentru a ajuta cât mai mulți moldoveni să afle unde pot vota la alegerile prezidențiale din 2020, de ce documente au nevoie și alte sfaturi utile.

**Comment by mihaelataranu7** [comment]
1 ноября 2020 состоятся выборы президента Республики Молдова. Граждане Молдовы с правом голоса, проживающие за границей, могут голосовать на избирательном участке.
Чтобы узнать, какие шаги необходимо предпринять, чтобы проголосовать в этом раунде выборов, ознакомьтесь с гидом ниже.

На президентских выборах только граждане Молдовы, проживающие или зарегистрированы за границей, реализуют свое право голоса за границей. Узнайте, что вам нужно сделать, чтобы проголосовать в стране вашего проживания на выборах 1 ноября 2020 года.

Важно!

Для голосования за границей необходимы следующие документы:
- Паспорт гражданина Республики Молдова, в том числе с истекшим сроком действия,
- Удостоверение личности (действительное) с сопроводительной картой
- Kнижка моряка.

Голосование будет проходить с 07.00 до 21.00 (по местному времени каждого избирательного участка).

Убедитесь, что у вас есть ручка и маска для лица. Каждый избирательный участок будет дезинфицироваться каждые 2-3 часа. На каждом избирательном участке количество избирателей, которые будут иметь доступ одновременно, будет равно количеству установленных кабин для голосования!


Где ты живешь?
Найдите в городе, где вы живете, ближайшие избирательные участки.

Сообщите своим друзьям!
Поделитесь этой информацией в социальных сетях, чтобы помочь как можно большему количеству молдаван узнать, где они могут проголосовать на президентских выборах 2020 года, какие документы им нужны и другие полезные советы.
