### ISSUE TITLE
Add language switch

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/vot-diaspora-client#17]
![image](https://user-images.githubusercontent.com/10476109/96971635-0d396700-151e-11eb-80f1-b4e0dd378858.png)

**Comment by johnsmithm** [comment]
use the code from here if needed https://github.com/code4romania/vot-romania-client

**Comment by vmelnic** [comment]
Hello,
Please review https://github.com/code4moldova/vot-diaspora-client/pull/22
