### ISSUE TITLE
Change the logo in the header and footer

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/vot-diaspora-client#2]
take the logo from here
https://www.figma.com/file/ro3AwDNZcYqWs86UHcEDtB/Code4.md-Website?node-id=113%3A652

**Comment by tacoelho** [comment]
I´ll take it.

**Comment by tacoelho** [comment]
All done @ Update Footer.vue #15

**Comment by johnsmithm** [comment]
any updates?
