### ISSUE TITLE
not https error for the api request

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/vot-diaspora-client#37]
when a request is made from votdiaspora.md to the API, we got this error

`7911c69.js:1 Mixed Content: The page at 'https://votdiaspora.md/' was loaded over HTTPS, but requested an insecure resource 'http://185.181.229.182:4000/api/polling-station/near-me?latitude=47.0246&longitude=28.83243'. This request has been blocked; the content must be served over HTTPS.`

need to create a proxy
- is there any methods in vue?
- can use netlify _redirects (already used for voluntar.md, info in readme [here](https://github.com/code4moldova/voluntar-web))

**Comment by unrevised6419** [comment]
voluntar.md is deployed on netlify, and netlify allows this proxy using `_redirects` file
For diaspora we use vercel, which does not allow the same stuff as netlify

The solution would be to add a proxy for diaspora backend in voluntar-web project
https://github.com/code4moldova/voluntar-web/blob/ed31b62eacea0a379b29545274c8976e38f2378d/scripts/generate-redirects.js#L14-L15
and use `https://voluntar.md/diaspora` as the api endpoint

**Comment by unrevised6419** [comment]
Fixed in
https://github.com/code4moldova/vot-diaspora-client/pull/40
and
https://github.com/code4moldova/voluntar-web/commit/ed31b62eacea0a379b29545274c8976e38f2378d
