### ISSUE TITLE
Change Navigation & Header Logos

### ISSUE THREAD

**Issue by andreivalcov** [code4moldova/vot-diaspora-client#53]
For Navigation use this logo version https://drive.google.com/file/d/1jEs6-GM4zP7kQWjNpsJNJv4DO-iKh32I/view?usp=sharing
For Header use this logo version: https://drive.google.com/file/d/1Ub9zz5vJpoLLklN2nliBcEfyQxasml_Y/view?usp=sharing

What it will look like:
![what it will look like](https://user-images.githubusercontent.com/72382254/97162093-635d1300-1787-11eb-906a-b10c894d5ff5.png)

**Comment by alexkingdom** [comment]
@andreivalcov I will do this

**Comment by alexkingdom** [comment]
![image](https://user-images.githubusercontent.com/57179803/97231089-a947c480-17e3-11eb-86ca-4c3331f653e2.png)

@andreivalcov seems ok. What do you think ?

**Comment by andreivalcov** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/57179803/97231089-a947c480-17e3-11eb-86ca-4c3331f653e2.png)
> 
> @andreivalcov seems ok. What do you think ?

Looks good, thanks 👍
