### ISSUE TITLE
Translate to russian

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/vot-diaspora-client#6]
delete hungarian and add russian

**Comment by mihaelataranu7** [comment]
Susține-ne
Diaspora este un proiect dezvoltat de o echipă de voluntari. În fiecare zi, zeci de prieteni și colegi lucrează la crearea unor instrumente digitale utile care să ne ușureze viața și să aducă Moldova mai aproape de progresul tehnologic. Ajută-ne să continuăm.

Поддержи нас
Диаспора - это проект, разработанный командой волонтеров. Каждый день десятки друзей и коллег твоих работают над созданием полезных цифровых инструментов, которые облегчат нам жизнь и приблизят Молдову к техническому прогрессу. Помогите нам продолжить.

**Comment by mihaelataranu7** [comment]
Informează-ți prietenii
Distribuie aceste informații în social media pentru a ajuta cât mai mulți moldoveni să afle unde pot vota la alegerile prezidențile din 2020, de ce documente au nevoie și alte sfaturi utile.

Сообщите своим друзьям
Поделитесь этой информацией в социальных сетях, чтобы помочь как можно большему количеству молдаван узнать, где  могут голосовать на на президентских выборах, 2020, какие документы им нужны и другие полезные советы.
