### ISSUE TITLE
change content for /despre page

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/vot-diaspora-client#9]

**Comment by mihaelataranu7** [comment]
Despre

Pe data de 1 noiembrie 2020 au loc alegerile prezidențiale din Republica Moldova. Cetățenii moldoveni cu drept de vot care au domiciliul sau reședința în străinătate pot vota la secție. Pentru a afla care sunt pașii pe care trebuie să-i parcurgeți pentru a putea alege în cadrul acestui tur electoral, consultați ghidul de mai jos.

Despre proiect

Vot Diaspora este o platformă care simplifică pe înțelesul cetățenilor ghidul electoral al alegerilor prezidențiale, care vor avea loc pe 1 noiembrie 2020. Vot Diaspora este un proiect elaborat de Code for Moldova, pentru a facilita accesul cetățenilor moldoveni de peste hotare la informație și a ajuta la o mai mare transparență a procesului electoral.

Accesând votdiaspora.md, toți cetățenii vor putea să verifice, alături de documentele și procedurile necesare pentru a vota la secție dacă se află în afara țării. Website-ul va fi disponibil cu informații actualizate la fiecare scrutin electoral. 

Vot Diaspora face parte din ecosistemul electoral dezvoltat de voluntarii Code for Moldova. Aplicația este preluată de la Code For Romania pro bono în cadrul Civic Labs, unul dintre programele prin care asociația proiectează soluții de tehnologie civică pentru problemele țării. 

Code for Moldova este o organizație non-profit care dezvoltă pro bono soluții digitale pentru a rezolva probleme sociale. Code for Moldova a ajuns în prezent la o comunitate de peste 90 de voluntari din sectorul IT care au dezvoltat aplicații web pentru Moldova, precum cele din ecosistemul voluntar.md și info.c19.md.

**Comment by mihaelataranu7** [comment]
1 ноября 2020 года состоятся выборы президента Республики Молдова. Граждане Молдовы с правом голоса, проживающие за границей, могут проголосовать на избирательном участке. Вы можете узнать, какие шаги нужно предпринять, чтобы иметь возможность проголосовать на ближайших выборах, ознакомившись с гидом ниже.

О проекте
Vot Diaspora - это платформа, которая помогает гражданам, находящимся за рубежом, в поиске информации по поводу избирательного процесса - президентских выборов, которые состоятся 1 ноября 2020 года. Vot Diaspora - это проект, разработанный организацией Code For Moldova, призванный облегчить доступ граждан Молдовы за рубежом к информации и обеспечить большую прозрачность избирательного процесса.

Зайдя на votdiaspora.md, все граждане смогут проверить адреса избирательных центров, наряду с документами и процедурами, необходимыми для голосования на избирательном участке, в случае нахождения за пределами страны. Веб-сайт будет предоставлять обновленную информацию по каждому избирательному циклу.
Vot Diaspora является частью избирательной экосистемы, разработанной волонтерами Code For Moldova. Концепция приложения была заимствована y Code For Romania, в рамках Civic Labs, одной из программ, в рамках которых ассоциация разрабатывает технологические решения для решения проблем страны и ее граждан.

Code for Moldova - это некоммерческая организация, которая на общественных началах разрабатывает цифровые решения для решения социальных проблем. Code For Moldova теперь достигла сообщества, состоящего из более чем 90 добровольцев из ИТ-сектора, которые разработали веб-приложения для Молдовы, например, из экосистемы voluntar.md и info.c19.md.

**Comment by YoSoySergio** [comment]
Ce facem cu sectiunea asta? 

![image](https://user-images.githubusercontent.com/10156144/97080015-02a3ce00-1601-11eb-9d2e-d4e60d80631f.png)
